conda:
  stage: deploy
  image: continuumio/miniconda3:latest
  tags:
    - docker
  script:
    - conda install -n base conda-build
    - conda list
    - conda --anaconda-upload build -c m-labs -c conda-forge -u quartiq conda
